Issue 123
janus-idp/software-templates pull request #149
Opened 2023-07-19 21:09 UTC by schultzp2020

## What does this PR do / why we need it

## Which issue(s) does this PR fix

Fixes https://github.com/janus-idp/software-templates/issues/123

## How to test changes / Special notes to the reviewer

2023-08-04 15:14 UTC, kadel requested changes

2023-08-04 15:14 UTC, kadel commented on scaffolder-templates/python-backend-template/template.yaml
> +          sourceControl: github.com
```suggestion
          sourceControl: gitlab.com
```

2023-08-04 15:14 UTC, kadel commented on scaffolder-templates/python-backend-template/template.yaml
> +          sourceControl: github.com
```suggestion
          sourceControl: gitlab.com
```

2023-08-04 15:14 UTC, kadel commented on scaffolder-templates/python-backend-template/skeleton/README.md
> +More information on the chosen CI method can be found [here](https://${{ values.sourceControl }}/${{ values.orgName }}/${{ values.repoName }}/blob/main/CI.md).
Is this supposed to be just an example? Because `CI.md` file doesn't exist in the skeleton.

2023-08-04 15:14 UTC, kadel commented on scaffolder-templates/python-backend-template/template.yaml
This is a pretty specific template for GitLab, not just by using it as a source control, but also using GitLab-CI.

It might be good to make this fact more visible by mentioning GitLab in description and/or adding "gitlab" to `tags`.

2023-08-11 18:22 UTC, schultzp2020 commented
@kadel PTAL?

2023-08-14 13:58 UTC, kadel requested changes
I just noticed that the gitlab-ci pipline is not working (sorry I did not catch this during the first pass). Suggested a few changes to make it work

2023-08-14 13:58 UTC, kadel commented on scaffolder-templates/python-backend-template/skeleton/.gitlab-ci.yml
> +        docker tag $CI_PROJECT_NAME $CI_PROJECT_NAME:$t
```suggestion
        docker tag $CI_PROJECT_NAME $REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$t
```

2023-08-16 19:28 UTC, schultzp2020 commented on scaffolder-templates/python-backend-template/skeleton/.gitlab-ci.yml
> +        docker push $CI_PROJECT_NAME:$t $REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
Whoops, I must've not saved the changes when I copied it from `docker tag`.

2023-08-16 19:29 UTC, schultzp2020 commented
@kadel PTAL?

2023-08-17 12:24 UTC, kadel approved these changes
LGTM

2023-08-21 17:50 UTC, christophe-f approved these changes

2023-08-21 17:50 UTC, merged