add register-component template
janus-idp/software-templates pull request #160
Opened 2023-07-28 16:27 UTC by kadel

## What does this PR do / why we need it

Adds template that allows users to register new component into the Backstage Service Catalog

## Which issue(s) does this PR fix

Fixes https://github.com/janus-idp/software-templates/issues/148

## How to test changes / Special notes to the reviewer

## What needs to be done before merging this PR:
 - [ ] useful README
 - [ ] probably better title and description

2023-08-03 14:04 UTC, kadel commented on scaffolder-skeletons/catalog-info-skeleton/catalog-info.yaml
> +  lifecycle: ${{ values.lifecycle }}
allowing to specify custom lifecycle, and using `production` as default for backward compatibility

2023-08-08 14:42 UTC, schultzp2020 commented on showcase-templates.yaml
> +    - https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/register-component/template.yaml
Missing new line

2023-08-08 14:43 UTC, schultzp2020 commented on scaffolder-templates/register-component/README.md
> +
Please remove extra lines

2023-08-08 14:45 UTC, schultzp2020 commented on scaffolder-templates/register-component/template.yaml
> +      id: fetchTemplate
```suggestion
      id: fetchRepository
```

2023-08-08 14:47 UTC, schultzp2020 commented on scaffolder-templates/register-component/template.yaml
> +    - id: template
```suggestion
    - id: catalogTemplate
```

2023-08-08 14:48 UTC, schultzp2020 commented on scaffolder-templates/register-component/template.yaml
> +    - id: template
Please reorder the parameters to be consistent with the other steps. Normally I like to do `id`, `name`, `action`.

2023-08-09 15:37 UTC, kadel commented on scaffolder-skeletons/catalog-info-skeleton/catalog-info.yaml
> +{%- if values.componentName %}
`componentName` is used in multiple places.
To avoid duplicating the same `if else` block, I have stored `name` in a new variable.

2023-08-11 18:24 UTC, schultzp2020 approved these changes
LGTM

2023-08-11 18:45 UTC, schultzp2020 requested changes

2023-08-11 18:45 UTC, schultzp2020 commented on scaffolder-templates/register-component/template.yaml
> +          componentName: ${{parameters.componentName}}
```suggestion
          componentName: ${{ parameters.componentName }}
```

2023-08-16 19:30 UTC, schultzp2020 approved these changes
LGTM

2023-08-16 19:30 UTC, schultzp2020 commented
@kadel can I merge?

2023-08-17 12:21 UTC, kadel commented
> @kadel can I merge?

Yes, everything is done from my side

2023-08-17 19:08 UTC, merged