Bump quarkus templates
janus-idp/software-templates pull request #194
Opened 2023-11-06 18:53 UTC by iocanel

## What does this PR do / why we need it

## Which issue(s) does this PR fix

Fixes #?

## How to test changes / Special notes to the reviewer

2023-11-06 18:54 UTC, iocanel commented
Created the pull request by accident before its ready, so I am converting to draft.

2023-11-10 12:13 UTC, kadel approved these changes

2023-11-10 14:45 UTC, schultzp2020 requested changes
Don't forget to update `java_package_name` to `javaPackageName` throughout the skeleton.

2023-11-10 14:45 UTC, schultzp2020 commented on templates/github/quarkus-backend/template.yaml
> +        - java_package_name
```suggestion
        - javaPackageName
```

Please use camelcase.

2023-11-10 14:45 UTC, schultzp2020 commented on templates/github/quarkus-backend/template.yaml
> +        java_package_name:
```suggestion
        javaPackageName:
```

2023-11-10 14:45 UTC, schultzp2020 commented on templates/github/quarkus-backend/template.yaml
> +          java_package_name: ${{ parameters.java_package_name }}
```suggestion
          javaPackageName: ${{ parameters.javaPackageName }}
```

2023-11-10 14:45 UTC, schultzp2020 commented on templates/github/quarkus-backend/template.yaml
> +          java_package_name: ${{ parameters.java_package_name }}
```suggestion
          javaPackageName: ${{ parameters.javaPackageName }}
```

2023-11-10 14:45 UTC, schultzp2020 commented on templates/github/quarkus-backend/template.yaml
> +          java_package_name: ${{ parameters.java_package_name }}
```suggestion
          javaPackageName: ${{ parameters.javaPackageName }}
```

2023-11-12 19:43 UTC, iocanel commented
@schultzp2020: Thanks for the feedback. Updated the PR to use camel case everywhere.

2023-11-15 14:43 UTC, schultzp2020 approved these changes
LGTM

2023-11-15 14:43 UTC, merged